### PR TITLE
Airbnb CSS homework

### PR DESCRIPTION
**Pull request by AOehmann239**
**Deliverable Submission**

Please describe your comfort and completeness levels before submitting.

Comfort Level (1-5): 1.55

Completeness Level (1-5): 1.5

Do you have any remaining questions about this deliverable?:
Felt like there was a more strategic way of going about this problem and found a sort of solution online and tried to shape my submission with the W3 example but not sure if it was correct.

### CODE REVIEW

**Comment by tkolsrud** [comment]
So it looks like your html is actually inside of your `.css` file, which is leaving you with just an h1 on the rendered page. Try dropping that into the html file and resubmitting, and then we can give you some notes on what might be a good next step!

**Comment by AOehmann239** [comment]
Hey Tom so my files for that project were all over the place and in
separate folders by accident so the html was in another folder and the
original untouched html file was in the folder I submitted.  After I
reorganized all the files and commited the changes and tried to git push
origin main I'm getting an error message

**Comment by AOehmann239** [comment]
You were right about the HTML being in the css as well, I honestly have no
idea what's going on with this assignment I'm sorry.  Trying to repair now.

**Comment by AOehmann239** [comment]
On branch main

Your branch is ahead of 'origin/main' by 2 commits.

  (use "git push" to publish your local commits)


Untracked files:

  (use "git add <file>..." to include in what will be committed)

.vscode/


nothing added to commit but untracked files present (use "git add" to track)

**Comment by AOehmann239** [comment]
Sorry this is such a pain.  Maybe tomorrow we can get in a call during a
break and fix this?  Sorry again!

Andrew

**Pull request closed without merging**
